import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Order, Customer, OrderLine, Product } from '../api/client';

export function generateInvoicePDF(
  order: Order & { customer?: Customer },
  orderLines: (OrderLine & { product?: Product })[]
) {
  // Create a new PDF document (A4 portrait)
  const doc = new jsPDF();
  const customer = order.customer;

  // Colors and styling
  const brandColor: [number, number, number] = [0, 82, 204]; // Approx brand blue
  const textDark: [number, number, number] = [30, 41, 59]; // slate-800
  const textLight: [number, number, number] = [100, 116, 139]; // slate-500

  // Header - Company Info
  doc.setFontSize(24);
  doc.setTextColor(...brandColor);
  doc.text('INVOICE', 14, 25);
  
  doc.setFontSize(10);
  doc.setTextColor(...textLight);
  doc.text('Two Brothers Food Complex P.L.C (2BFC)', 14, 32);
  doc.text('Adama, Ethiopia', 14, 38);
  doc.text('Phone: +251-11-222-3333', 14, 44);

  // Header - Invoice Details
  doc.setFontSize(10);
  doc.setTextColor(...textDark);
  doc.text(`Order Number:`, 130, 25);
  doc.setFont(undefined, 'bold');
  doc.text(order.order_number, 160, 25);
  
  doc.setFont(undefined, 'normal');
  doc.text(`Date:`, 130, 32);
  doc.text(new Date(order.order_date).toLocaleDateString(), 160, 32);
  
  doc.text(`Status:`, 130, 39);
  doc.text(order.status.replace(/_/g, ' ').toUpperCase(), 160, 39);

  // Customer Info block
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.setFillColor(248, 250, 252); // slate-50
  doc.roundedRect(14, 55, 90, 40, 3, 3, 'FD');
  
  doc.setFontSize(11);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(...textDark);
  doc.text('Billed To:', 18, 63);
  
  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  if (customer) {
    doc.text(customer.name, 18, 70);
    doc.text(customer.phone || 'No phone', 18, 77);
    doc.text(customer.address || 'No address provided', 18, 84, { maxWidth: 80 });
  } else {
    doc.text('Unknown Customer', 18, 70);
  }

  // Order Lines Table
  const tableData = orderLines.map(line => [
    line.product?.sku || 'Unknown',
    line.product?.name || 'Unknown Product',
    line.quantity_boxes.toString(),
    line.quantity_units.toString(),
    line.quantity_fulfilled_units.toString()
  ]);

  autoTable(doc, {
    startY: 110,
    head: [['SKU', 'Product Name', 'Boxes', 'Total Units', 'Fulfilled Units']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: brandColor,
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    styles: {
      fontSize: 10,
      textColor: textDark,
      cellPadding: 6
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252] // slate-50
    }
  });

  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(9);
  doc.setTextColor(...textLight);
  doc.text('Generated by 2BFC Warehouse Management System', 14, pageHeight - 15);
  doc.text(`Page 1 of 1`, 180, pageHeight - 15);

  // Save the PDF
  doc.save(`Invoice_${order.order_number}.pdf`);
}
